export const {
  NEXT_PUBLIC_REQUEST_API_URL,
  NEXT_PUBLIC_BACK_API_URL,
  NEXT_PUBLIC_CLOUDINARY_API_URL,
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET,
  NEXT_PUBLIC_CLOUDINARY_API_KEY,
  NEXT_PUBLIC_CLOUDINARY_API_SECRET
} = process.env
