import './globals.css'
import 'react-quill/dist/quill.snow.css'
import './quill.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import WebPage from '@/app/components/WebPage'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <WebPage>
            {children}
          </WebPage>
        </Providers>
      </body>
    </html>
  )
}
